apiVersion: v1
kind: Pod
metadata:
  name: test-sidecar-no-init
  namespace: test-policy
  labels:
    app: test
  annotations:
    sidecar.istio.io/inject: "true"
    traffic.sidecar.istio.io/includeInboundPorts: ""
    traffic.sidecar.istio.io/excludeInboundPorts: "*"
spec:
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80