apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: test-policy
spec:
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  reinvocationPolicy: "Never"
  mutations:
  - patchType: "ApplyConfiguration"
    applyConfiguration:
      expression: |
        Object{
          metadata: Object.metadata{
            labels: {"test": "added-by-policy"}
          }
        }
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: test-policy-binding
spec:
  policyName: test-policy
  matchResources:
    resourceRules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]