apiVersion: v1
kind: Pod
metadata:
  name: test-no-injection
  namespace: test-policy
  labels:
    app: test
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: app
    image: nginx:alpine
    ports:
    - containerPort: 80